index_table_avs = [
    "background",
    "ambulance_siren",
    "baby_laughter",
    "cap_gun_shooting",
    "cat_meowing",
    "chainsawing_trees",
    "coyote_howling",
    "dog_barking",
    "driving_buses",
    "female_singing",
    "helicopter",
    "horse_clip-clop",
    "lawn_mowing",
    "lions_roaring",
    "male_speech",
    "mynah_bird_singing",
    "playing_acoustic_guitar",
    "playing_glockenspiel",
    "playing_piano",
    "playing_tabla",
    "playing_ukulele",
    "playing_violin",
    "race_car",
    "typing_on_computer_keyboard",
]
index_table_coco = [
    "background",
    "airplane",
    "baby",
    "bird",
    "bus",
    "car",
    "cat",
    "cell phone",
    "cow",
    "dog",
    "elephant",
    "female",
    "horse",
    "keyboard",
    "male",
    "motorcycle",
    "mouse",
    "sheep",
    "skateboard",
    "sports ball",
    "tennis racket",
    "zebra",
]

coco_class_dict = {
    # 1: "person",
    "5": "airplane",
    "16": "bird",
    "6": "bus",
    "3": "car",
    "17": "cat",
    "77": "cell phone",
    "21": "cow",
    "18": "dog",
    "22": "elephant",
    "19": "horse",
    "76": "keyboard",
    "4": "motorcycle",
    "74": "mouse",
    "20": "sheep",
    "41": "skateboard",
    "37": "sports ball",
    "43": "tennis racket",
    "24": "zebra",
    "92": "male",
    "93": "female",
    "94": "baby",
}

index_table_coco_org = [
    "background",
    "airplane",
    "bird",
    "bus",
    "car",
    "cat",
    "cell phone",
    "cow",
    "dog",
    "elephant",
    "horse",
    "keyboard",
    "person",
    "motorcycle",
    "mouse",
    "sheep",
    "skateboard",
    "sports ball",
    "tennis racket",
    "zebra",
]

coco_class_dict_org = {
    "1": "person",
    "5": "airplane",
    "16": "bird",
    "6": "bus",
    "3": "car",
    "17": "cat",
    "77": "cell phone",
    "21": "cow",
    "18": "dog",
    "22": "elephant",
    "19": "horse",
    "76": "keyboard",
    "4": "motorcycle",
    "74": "mouse",
    "20": "sheep",
    "41": "skateboard",
    "37": "sports ball",
    "43": "tennis racket",
    "24": "zebra",
}
